name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: "Build cs16"
        run: |
          DOCKER_IMAGE="ghcr.io/loong64/debian:trixie"
          DOCKER_CMD=`cat << EOF
            set -e
            apt update
            apt install -y build-essential cmake ninja-build libfontconfig-dev
            mkdir build
            cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
            cd build
            cmake --build . --parallel $(nproc)
            cpack --config CPackConfig.cmake
          EOF
          `
          docker run --rm \
            --cpus=`nproc` \
            --platform linux/loong64 \
            --volume /tmp/.cache:/root/.cache \
            --volume "$(pwd):/io" \
            --workdir /io \
            "$DOCKER_IMAGE" \
            bash -c "$DOCKER_CMD"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ matrix.arch }}
          path: build/*.tar.gz

